{{- if .Values.celeryWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-service.fullname" . }}-celery
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-worker
spec:
  replicas: {{ .Values.celeryWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "order-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-worker
  template:
    metadata:
      labels:
        {{- include "order-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery-worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: celery-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery", "-A", "app.worker.celery_app", "worker", "--loglevel=info", "--concurrency=2"]
          envFrom:
            - configMapRef:
                name: {{ include "order-service.fullname" . }}
            - secretRef:
                name: {{ include "order-service.fullname" . }}
          resources:
            {{- toYaml .Values.celeryWorker.resources | nindent 12 }}
{{- end }}
